# Generated by Django 4.0 on 2024-10-30 06:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('return_page', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='신규로 등록할 회사명 입력', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(blank=True, max_length=15)),
                ('grade', models.CharField(blank=True, max_length=15)),
                ('permission', models.CharField(blank=True, choices=[('M', '관리자'), ('P', '프로젝트담당자'), ('G', '일반사용자')], max_length=1)),
                ('req_date', models.DateField(blank=True, null=True)),
                ('gen_date', models.DateField(blank=True, null=True)),
                ('ret_date', models.DateField(blank=True, null=True)),
                ('del_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('N', '투입 진행중'), ('P', '투입'), ('D', '철수'), ('O', '철수 진행중')], max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('vdi_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('empID', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='프로젝트명 입력', max_length=200)),
                ('yn', models.CharField(help_text='종료여부', max_length=1)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='auth.user')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='secUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('usergrade', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=5000, null=True)),
                ('date_of_start', models.DateField(blank=True, null=True, verbose_name='투입일자')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='철수일자')),
                ('status', models.CharField(blank=True, choices=[('N', '신규요청'), ('P', '승인진행중'), ('G', '승인완료'), ('D', '반려')], default='N', max_length=1)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
                ('project', models.ForeignKey(help_text='소속 프로젝트 선택', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.project')),
                ('req_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, help_text='Enter IP Address', max_length=20, null=True)),
                ('memo', models.TextField(blank=True, help_text='Memo', max_length=5000, null=True)),
                ('date_of_req', models.DateField(blank=True, null=True, verbose_name='투입일자')),
                ('status', models.CharField(blank=True, choices=[('N', '신규요청'), ('P', '승인진행중'), ('G', '승인완료'), ('D', '반려')], default='N', max_length=1)),
                ('req_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('type_name', models.CharField(blank=True, max_length=20, null=True)),
                ('type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Description', max_length=5000, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.CharField(blank=True, choices=[('V', 'VDI'), ('D', 'DB Safer'), ('S', '서버접근제어'), ('A', 'NAS'), ('E', '기타')], max_length=1, null=True)),
                ('in_use', models.CharField(blank=True, max_length=1, null=True)),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_start', models.DateTimeField(blank=True, null=True)),
                ('date_of_end', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=1)),
                ('signdate', models.DateField(blank=True, null=True)),
                ('loginuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRetireApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=1, null=True)),
                ('final', models.CharField(blank=True, max_length=1, null=True)),
                ('approved', models.CharField(blank=True, max_length=1, null=True)),
                ('comment', models.TextField(blank=True, help_text='Comment', max_length=1000, null=True)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('retiree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserRetire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('comment', models.TextField(blank=True, help_text='Comment', max_length=1000, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.usercode')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('retiree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestApproveMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.userrequesttypemaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=1, null=True)),
                ('final', models.CharField(blank=True, max_length=1, null=True)),
                ('approved', models.CharField(blank=True, max_length=1, null=True)),
                ('comment', models.TextField(blank=True, help_text='Comment', max_length=1000, null=True)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('req_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.userrequest')),
            ],
        ),
        migrations.AddField(
            model_name='userrequest',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.userrequesttypemaster'),
        ),
        migrations.CreateModel(
            name='SecUserApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=1, null=True)),
                ('final', models.CharField(blank=True, max_length=1, null=True)),
                ('approved', models.CharField(blank=True, max_length=1, null=True)),
                ('approve_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_list', to='auth.user')),
                ('user_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.secuser')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.CreateModel(
            name='ExcelUploadRecord',
            fields=[
                ('company', models.CharField(max_length=50)),
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('year_month', models.CharField(max_length=7)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('num_record', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=4)),
                ('yyyymm', models.CharField(max_length=6)),
                ('account', models.CharField(max_length=12)),
                ('account_name', models.CharField(max_length=50)),
                ('account_value', models.BigIntegerField()),
                ('upload_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.exceluploadrecord')),
            ],
        ),
    ]
