# Generated by Django 4.0 on 2024-10-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default=1001, help_text='신규로 등록할 회사코드(4자리) 입력', max_length=4),
            preserve_default=False,
        ),
    ]
